language: node_js
node_js:
  - "node"

after_script:
  - grunt
  - cd ./dist
  - git init
  - git config user.name "xiaoxuqin"
  - git config user.email "2837303093@qq.com"
  - git add .
  - git commit -m "baidu_register_auto"
  - git push --force --quiet "https://${ACC_TOKEN}@${GH_REF}" master:${BRANCH}

branches:
  only:
    - master